name: Reusable workflow example

on:
  push:
    branches:
      - main

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: octo-org/my-action@v1
